server:
  port: 3000

db:
  host: '127.0.0.1'
  port: 5432
  type: 'postgres'
  database: 'coffy'
  username: 'postgres'
  password: 'admin'
  synchronize: true

bcrypt:
  saltRounds: 10

jwt: 
  expiresIn: 5184000s
  secret: 'coffy-secret'

s3:
  accessKeyId: AKIAJGJQQFZJ6XHI7Y2A
  secretAccessKey: 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
  region: us-east-2
  bucketName: coffy-source
  timeout: 300