export enum AccessControlList {
  ALL = "ALL",
  DEFAULT = "DEFAULT",
  /**
   * USER
   */
  USER_CREATE = "USER_CREATE",
  USER_READ = "USER_READ",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",
  USER_PERMANENTLY_DELETE = "USER_PERMANENTLY_DELETE",
  SELF_USER_READ = "SELF_USER_READ",
  SELF_USER_UPDATE = "SELF_USER_UPDATE",
  SELF_USER_DELETE = "SELF_USER_DELETE",
  SELF_USER_PERMANENTLY_DELETE = "SELF_USER_PERMANENTLY_DELETE",

  /**
   * DESTINATION
   */
  DESTINATION_CREATE = "DESTINATION_CREATE",
  DESTINATION_READ = "DESTINATION_READ",
  DESTINATION_UPDATE = "DESTINATION_UPDATE",
  DESTINATION_DELETE = "DESTINATION_DELETE",
  DESTINATION_PERMANENTLY_DELETE = "DESTINATION_PERMANENTLY_DELETE",
  SELF_DESTINATION_READ = "SELF_DESTINATION_READ",
  SELF_DESTINATION_UPDATE = "SELF_DESTINATION_UPDATE",
  SELF_DESTINATION_DELETE = "SELF_DESTINATION_DELETE",
  SELF_DESTINATION_PERMANENTLY_DELETE = "SELF_DESTINATION_PERMANENTLY_DELETE",

  /**
   * SERVICE_CATEGORY
   */
  SERVICE_CATEGORY_CREATE = "SERVICE_CATEGORY_CREATE",
  SERVICE_CATEGORY_READ = "SERVICE_CATEGORY_READ",
  SERVICE_CATEGORY_UPDATE = "SERVICE_CATEGORY_UPDATE",
  SERVICE_CATEGORY_DELETE = "SERVICE_CATEGORY_DELETE",
  SERVICE_CATEGORY_PERMANENTLY_DELETE = "SERVICE_CATEGORY_PERMANENTLY_DELETE",
  SELF_SERVICE_CATEGORY_READ = "SELF_SERVICE_CATEGORY_READ",
  SELF_SERVICE_CATEGORY_UPDATE = "SELF_SERVICE_CATEGORY_UPDATE",
  SELF_SERVICE_CATEGORY_DELETE = "SELF_SERVICE_CATEGORY_DELETE",
  SELF_SERVICE_CATEGORY_PERMANENTLY_DELETE = "SELF_SERVICE_CATEGORY_PERMANENTLY_DELETE",
}
