export enum AccessControlList {
  ALL = 'ALL',
  /**
   * USER
   */
  USER_CREATE = 'USER_CREATE',
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_PERMANENTLY_DELETE = 'USER_PERMANENTLY_DELETE',
  SELF_USER_READ = 'SELF_USER_READ',
  SELF_USER_UPDATE = 'SELF_USER_UPDATE',
  SELF_USER_DELETE = 'SELF_USER_DELETE',
  SELF_USER_PERMANENTLY_DELETE = 'SELF_USER_PERMANENTLY_DELETE',

  /**
   * CATEGORY
   */
  CATEGORY_CREATE = 'CATEGORY_CREATE',
  CATEGORY_READ = 'CATEGORY_READ',
  CATEGORY_UPDATE = 'CATEGORY_UPDATE',
  CATEGORY_DELETE = 'CATEGORY_DELETE',
  CATEGORY_PERMANENTLY_DELETE = 'CATEGORY_PERMANENTLY_DELETE',
  SELF_CATEGORY_READ = 'SELF_CATEGORY_READ',
  SELF_CATEGORY_UPDATE = 'SELF_CATEGORY_UPDATE',
  SELF_CATEGORY_DELETE = 'SELF_CATEGORY_DELETE',
  SELF_CATEGORY_PERMANENTLY_DELETE = 'SELF_CATEGORY_PERMANENTLY_DELETE',

  /**
   * PRODUCT
   */
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_READ = 'PRODUCT_READ',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_DELETE = 'PRODUCT_DELETE',
  PRODUCT_PERMANENTLY_DELETE = 'PRODUCT_PERMANENTLY_DELETE',
  SELF_PRODUCT_READ = 'SELF_PRODUCT_READ',
  SELF_PRODUCT_UPDATE = 'SELF_PRODUCT_UPDATE',
  SELF_PRODUCT_DELETE = 'SELF_PRODUCT_DELETE',
  SELF_PRODUCT_PERMANENTLY_DELETE = 'SELF_PRODUCT_PERMANENTLY_DELETE',
}
