export enum AccessControlList {
  ALL = 'ALL',

  /**
   * ROLE
   */
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_READ = 'ROLE_READ',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_PERMANENTLY_DELETE = 'ROLE_PERMANENTLY_DELETE',


  /**
   * USER
   */
  USER_CREATE = 'USER_CREATE',
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_PERMANENTLY_DELETE = 'USER_PERMANENTLY_DELETE',

  /**
   * CATEGORY
   */
  CATEGORY_CREATE = 'CATEGORY_CREATE',
  CATEGORY_READ = 'CATEGORY_READ',
  CATEGORY_UPDATE = 'CATEGORY_UPDATE',
  CATEGORY_DELETE = 'CATEGORY_DELETE',
  CATEGORY_PERMANENTLY_DELETE = 'CATEGORY_PERMANENTLY_DELETE',

  /**
   * PRODUCT
   */
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_READ = 'PRODUCT_READ',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_DELETE = 'PRODUCT_DELETE',
  PRODUCT_PERMANENTLY_DELETE = 'PRODUCT_PERMANENTLY_DELETE',

  /**
   * PRODUCT
   */
  BILL_CREATE = 'BILL_CREATE',
  BILL_READ = 'BILL_READ',
  BILL_UPDATE = 'BILL_UPDATE',
  BILL_DELETE = 'BILL_DELETE',
  BILL_PERMANENTLY_DELETE = 'BILL_PERMANENTLY_DELETE',
}
