export enum CrudName {
  ALL = 'ALL',
  GET_MANY = 'GET_MANY',
  GET_TRASHED = 'GET_TRASHED',
  GET_ONE = 'GET_ONE',
  CREATE_ONE = 'CREATE_ONE',
  CREATE_MANY = 'CREATE_MANY',
  UPDATE_ONE = 'UPDATE_ONE',
  DELETE_ONE = 'DELETE_ONE',
  DELETE_ONE_PERMANENTLY = 'DELETE_ONE_PERMANENTLY',
  RESTORE_ONE = 'RESTORE_ONE',
}
